services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    user: root
    container_name: 'proxy-manager'
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8100:81' # Admin Web Port
    environment:
      DB_SQLITE_FILE: '/data/database.sqlite'
    volumes:
      - ./proxy/custom:/data/nginx/custom
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
